export const messageError = {
    CONNECT_NO_PERMISSION: 'CONNECT_NO_PERMISSION',
    EQUIPMENT_OUT_OF_LIMIT: 'EQUIPMENT_OUT_OF_LIMIT',
    MISSING_FIELD_ID: 'MISSING_FIELD_ID',
    MISSING_FIELD_TYPE: 'MISSING_FIELD_TYPE',
    MISSING_FIELD_METHOD: 'MISSING_FIELD_METHOD',
    MISSING_FIELD_DATA: 'MISSING_FIELD_DATA',
    MISSING_FIELD_SERVICE: 'MISSING_FIELD_SERVICE',

    FORBIDDEN: 'FORBIDDEN',
    GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
    INVALID_MESSAGE: 'INVALID_MESSAGE',
    INVALID_MESSAGE_TYPE: 'INVALID_MESSAGE_TYPE'
};
